import json
import unittest
from types import SimpleNamespace

from finengine.export_supabase import (
    SupabaseExporter, canonical_dimensions, facts_to_sql, flatten_fact,
)
from finengine.models import Market


def _company():
    return SimpleNamespace(company_id="sa:2222", symbol="2222", market=Market("SA"))


_SOURCED_FACT = {
    "metric": "accounts_payable", "display_name": "Accounts payable",
    "category": "balance_sheet", "statement": "balance_sheet",
    "value": "17103449000", "value_type": "decimal", "currency": "SAR", "unit": "SAR",
    "period_end": "2025-12-31", "period_kind": "instant", "fiscal_year": 2025,
    "fiscal_quarter": None, "scope": "consolidated", "dimensions": {},
    "quality_score": 1.0, "is_calculated": False, "calculation": None,
    "source_url": "https://issuer.example/fy-2025.pdf", "filed_at": "2026-03-03",
    "source_key": "file:abc123",
    "provenance": {
        "source": {
            "source_url": "https://issuer.example/fy-2025.pdf", "filed_at": "2026-03-03",
            "archived_path": "data\\raw\\SA\\2222\\documents\\deadbeef.pdf",
            "artifact_sha256": "deadbeef",
        },
        "extraction": {
            "raw_label": "Trade payables", "raw_value": "17103449", "page": 132,
            "table_ref": None, "confidence": "1.0", "mapping_method": "exact_dictionary",
        },
    },
}

_CALC_FACT = {
    "metric": "free_cash_flow", "display_name": "Free cash flow", "category": "calculated",
    "statement": "cash_flow", "value": "7208971000", "value_type": "decimal",
    "currency": "SAR", "unit": "SAR", "period_end": "2025-12-31", "period_kind": "fy",
    "fiscal_year": 2025, "fiscal_quarter": None, "scope": "consolidated", "dimensions": {},
    "quality_score": 1.0, "is_calculated": True,
    "calculation": "operating_cash_flow - abs(capex)", "source_url": None, "filed_at": None,
    "source_key": "file:abc123",
    "provenance": {"source": {}, "derivation": {"type": "deterministic_calculation",
                                               "calculation": "operating_cash_flow - abs(capex)"}},
}


class FlattenTests(unittest.TestCase):
    def test_sourced_fact_carries_full_provenance(self):
        row = flatten_fact(_company(), _SOURCED_FACT, engine_version="1.5.0", synced_at="2026-09-05T00:00:00+00:00")
        self.assertEqual(row["company_id"], "sa:2222")
        self.assertEqual(row["ticker"], "2222")
        self.assertEqual(row["value"], "17103449000")          # exact string, no float
        self.assertEqual(row["report_page"], 132)
        self.assertEqual(row["extraction_label"], "Trade payables")
        self.assertEqual(row["extraction_value"], "17103449")
        self.assertEqual(row["mapping_confidence"], "1.0")
        self.assertEqual(row["mapping_method"], "exact_dictionary")
        self.assertEqual(row["archived_path"], "data/raw/SA/2222/documents/deadbeef.pdf")
        self.assertEqual(row["archived_sha256"], "deadbeef")
        self.assertFalse(row["is_calculated"])

    def test_calculated_fact_carries_formula_not_extraction(self):
        row = flatten_fact(_company(), _CALC_FACT, engine_version="1.5.0", synced_at="2026-09-05T00:00:00+00:00")
        self.assertTrue(row["is_calculated"])
        self.assertEqual(row["calculation"], "operating_cash_flow - abs(capex)")
        self.assertIsNone(row["extraction_label"])
        self.assertIsNone(row["report_page"])

    def test_dimensions_key_is_stable_and_order_independent(self):
        self.assertEqual(canonical_dimensions({}), "")
        self.assertEqual(
            canonical_dimensions({"segment": "upstream", "geography": "ksa"}),
            canonical_dimensions({"geography": "ksa", "segment": "upstream"}),
        )


class SqlTests(unittest.TestCase):
    def test_emits_idempotent_upsert(self):
        rows = [flatten_fact(_company(), _SOURCED_FACT, engine_version="1.5.0", synced_at="2026-09-05T00:00:00+00:00")]
        sql = facts_to_sql(rows)
        self.assertIn("insert into public.financial_facts", sql)
        self.assertIn("on conflict (company_id,metric,period_end,period_kind,scope,dimensions_key) do update set", sql)
        self.assertIn("'Trade payables'", sql)
        self.assertTrue(sql.strip().startswith("-- generated by finengine export-supabase"))
        self.assertIn("begin;", sql)
        self.assertIn("commit;", sql)

    def test_empty_rows_is_a_noop_script(self):
        self.assertIn("no current facts", facts_to_sql([]))

    def test_sql_escapes_apostrophes(self):
        fact = dict(_SOURCED_FACT)
        fact["provenance"] = json.loads(json.dumps(_SOURCED_FACT["provenance"]))
        fact["provenance"]["extraction"]["raw_label"] = "Owners' equity"
        sql = facts_to_sql([flatten_fact(_company(), fact, engine_version="x", synced_at="t")])
        self.assertIn("'Owners'' equity'", sql)


class UpsertTransportTests(unittest.TestCase):
    def test_upsert_posts_batches_with_service_key_and_conflict_target(self):
        calls = []

        class _Resp:
            def __enter__(self): return self
            def __exit__(self, *a): return False
            def read(self): return b"[]"

        def opener(request, timeout=None):
            calls.append(request)
            return _Resp()

        exporter = SupabaseExporter(
            "unused.sqlite3", "https://proj.supabase.co", "service-key-xyz",
            engine_version="1.5.0", opener=opener,
        )
        rows = [flatten_fact(_company(), _SOURCED_FACT, engine_version="1.5.0", synced_at="t")]
        exporter._upsert(rows)

        self.assertEqual(len(calls), 1)
        request = calls[0]
        self.assertEqual(request.method, "POST")
        self.assertIn("on_conflict=company_id,metric,period_end,period_kind,scope,dimensions_key", request.full_url)
        self.assertEqual(request.headers["Apikey"], "service-key-xyz")
        self.assertEqual(request.headers["Authorization"], "Bearer service-key-xyz")
        self.assertIn("merge-duplicates", request.headers["Prefer"])
        sent = json.loads(request.data)
        self.assertEqual(sent[0]["metric"], "accounts_payable")

    def test_constructor_rejects_missing_credentials(self):
        with self.assertRaises(ValueError):
            SupabaseExporter("db", "", "key", engine_version="x")
        with self.assertRaises(ValueError):
            SupabaseExporter("db", "https://x.supabase.co", "", engine_version="x")


if __name__ == "__main__":
    unittest.main()
